// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34014
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PMLib_OutsideIn_Start_Specs.Egenskaper
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Som en filmsamlare vill jag kunna lägga till filmtitlar så att jag kan sätta upp " +
        "en ny samling")]
    public partial class SomEnFilmsamlareVillJagKunnaLaggaTillFilmtitlarSaAttJagKanSattaUppEnNySamlingFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "lista_litet_filmbibliotek.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("sv-SE"), "Som en filmsamlare vill jag kunna lägga till filmtitlar så att jag kan sätta upp " +
                    "en ny samling", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Lägga till filmer")]
        public virtual void LaggaTillFilmer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Lägga till filmer", ((string[])(null)));
#line 5
  this.ScenarioSetup(scenarioInfo);
#line 6
    testRunner.Given("att filmbiblioteket är tomt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Givet ");
#line 7
    testRunner.When("jag lägger till filmerna \"Jaws,Star Wars,Alien\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "När ");
#line 8
    testRunner.When("jag listar alla filmer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "När ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Titel"});
            table1.AddRow(new string[] {
                        "Jaws"});
            table1.AddRow(new string[] {
                        "Star Wars"});
            table1.AddRow(new string[] {
                        "Alien"});
#line 9
    testRunner.Then("ska listan se ut så här:", ((string)(null)), table1, "Så ");
#line 14
 testRunner.And("meddelandet \"Antal filmer i samlingen 3.\" visas på skärmen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Och ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
